### ISSUE TITLE
Can't reorder

### ISSUE THREAD

**Issue by Thomas-O** [JonathanHolvey/plugin.audio.streaming-radio#5]
I am unable to change the ascending / descending order of the radio stations in either of my two skins: confluence and eminence. Nor is it possible to list the stations by any order: name, date added etc.

Is there something I can add to the.xml so that I can order to my preference?

**Comment by JonathanHolvey** [comment]
I've added an option to override the default sort order by providing an explicit `<sort>` option in the XML file. Ascending and descending sort also work now, in addition to a couple of extra sorting options.

This is available from version 1.3.0.
