### ISSUE TITLE
Can't install zip on Jarvis

### ISSUE THREAD

**Issue by Thomas-O** [JonathanHolvey/plugin.audio.streaming-radio#8]
I can't install the zip on Jarvis. However, it's installing and working fine on Krypton beta.

**Comment by Thomas-O** [comment]
The problem with Jarvis only with the Android app. Just tried it on the OpenElec Jarvis for Wetek Core and it's fine.

**Comment by JonathanHolvey** [comment]
Just tested this. The plugin installs correctly but fails to run due to a Python version incompatibility. Python 2.6 and earlier throws `ValueError: zero length field name in format` when positional arguments are omitted from a formatted string. This should be easy to fix.
